import { describe, expect, it } from 'vitest'
import { buildRegistryGraphFromFiles } from './registry-graph.js'
import { renderOpenRouterProviderDetail, renderOpenRouterProviderIndex, renderOpenRouterRawDetail, renderOpenRouterRawHome } from './openrouter-raw-renderer.js'

describe('registry graph adapter', () => {
  const graph = buildRegistryGraphFromFiles()

  it('adapts data/models.json and data/providers/*.json to the plaza graph contract', () => {
    expect(graph.stats.sourceNodes).toBeGreaterThan(300)
    expect(graph.stats.endpointNodes).toBeGreaterThan(1000)
    expect(graph.stats.pricingObservations).toBeGreaterThan(1000)
    expect(graph.nodes.find((node) => node.route === '/openai/gpt-5.5')).toBeTruthy()
    expect(graph.nodes.find((node) => node.route === '/z-ai/glm-4.5')).toBeTruthy()
    expect(graph.schema.urlShape).toBe('/<provider>/<model-id>')
  })

  it('renders the current plaza, provider, and detail UI from the new registry graph', () => {
    const home = renderOpenRouterRawHome(graph)
    const writerVisibleRows = [...home.matchAll(/<tr data-model-row data-search-only="false"[^>]*data-model-author="writer"[\s\S]*?<\/tr>/gu)].map((match) => match[0])
    expect(writerVisibleRows).toHaveLength(1)
    expect(writerVisibleRows[0]).toContain('href="/writer/palmyra-x5/"')
    expect(writerVisibleRows[0]).not.toContain('href="/openrouter/palmyra-x5/"')
    expect(writerVisibleRows[0]).not.toContain('href="/amazon/palmyra-x5/"')
    expect(writerVisibleRows[0]).toContain('data-price-source-provider=')
    expect(writerVisibleRows[0]).toContain('priceValue')
    const provider = renderOpenRouterProviderDetail(graph, 'openai')
    const providerIndex = renderOpenRouterProviderIndex(graph)
    const novitaProvider = renderOpenRouterProviderDetail(graph, 'novita')
    const deepInfraProvider = renderOpenRouterProviderDetail(graph, 'deepinfra')
    const node = graph.nodes.find((candidate) => candidate.route === '/openai/gpt-5.5')
    expect(node).toBeTruthy()
    const detail = renderOpenRouterRawDetail(graph, node!)
    const titledNode = graph.nodes.find((candidate) => candidate.route === '/anthropic/claude-opus-4.6')
    expect(titledNode).toBeTruthy()
    const titledDetail = renderOpenRouterRawDetail(graph, titledNode!)

    expect(home).toContain('模型广场')
    expect(home).toContain('data-model-row')
    expect(home).toContain('GPT-5.5')
    expect(home).not.toContain('/new-models/')
    expect(provider).toContain('OpenAI')
    expect(provider).toContain('class="modelsShell providerShell"')
    expect(provider).toContain('<span>厂牌</span>')
    expect(provider).toContain('class="modelTable"')
    expect(provider).not.toContain('返回模型广场')
    expect(provider).not.toContain('个模型 / offer')
    expect(providerIndex).toContain('href="/novita/"')
    expect(providerIndex).toContain('自研 ')
    expect(providerIndex).toContain('提供 ')
    expect(novitaProvider).toContain('<h1>Novita</h1>')
    expect(novitaProvider).toContain('class="modelsShell providerShell"')
    expect(novitaProvider).toContain('class="modelTable"')
    expect(novitaProvider).toContain('data-model-row')
    expect(novitaProvider).toContain('DeepSeek')
    expect(novitaProvider).not.toContain('个模型 / offer')
    expect(deepInfraProvider).toContain('<h1>DeepInfra</h1>')
    expect(deepInfraProvider).toContain('class="modelTable"')
    expect(detail).toContain('Model ID')
    expect(detail).toContain('价格')
    expect(detail).toContain('数据来源与源数据')
    expect(titledNode!.displayName).toBe('Claude Opus 4.6')
    expect(titledDetail).toContain('<h1>Anthropic: Claude Opus 4.6</h1>')
    expect(titledDetail).toContain('<title>Anthropic: Claude Opus 4.6 · mddb.dev</title>')
    const openRouterEndpoint = graph.nodes.find((candidate) => candidate.route === '/openrouter/solar-pro-3')
    expect(openRouterEndpoint).toBeTruthy()
    const openRouterEndpointDetail = renderOpenRouterRawDetail(graph, openRouterEndpoint!)
    expect(openRouterEndpoint!.displayName).toBe('Solar Pro 3')
    expect(openRouterEndpointDetail).toContain('<h1>Upstage: Solar Pro 3</h1>')
    expect(openRouterEndpointDetail).toContain('<title>Upstage: Solar Pro 3 · mddb.dev</title>')
    expect(openRouterEndpointDetail).toContain('Provider · OpenRouter')
    expect(openRouterEndpointDetail).not.toContain('class="relationChips"')
    expect(openRouterEndpointDetail).toContain('查看 canonical 模型页')
    expect(openRouterEndpointDetail).not.toContain('Outgoing raw edges')
    expect(openRouterEndpointDetail).not.toContain('Incoming raw edges')
    const selfProviderEndpoint = graph.nodes.find((candidate) => candidate.route === '/openai/gpt-5.5')
    expect(selfProviderEndpoint).toBeTruthy()
    const selfProviderEndpointDetail = renderOpenRouterRawDetail(graph, selfProviderEndpoint!)
    expect(selfProviderEndpointDetail).toContain('<h1>OpenAI: GPT-5.5</h1>')
    expect(selfProviderEndpointDetail).toContain('Author · openai')
    expect(selfProviderEndpointDetail).not.toContain('当前是 provider deployment 页面')
    expect(selfProviderEndpointDetail).not.toContain('查看 canonical 模型页')
    const selfProviderEndpointRoute = graph.nodes.find((candidate) => candidate.route === '/openai/gpt-5.5/endpoint')
    expect(selfProviderEndpointRoute).toBeTruthy()
    expect(selfProviderEndpointDetail).not.toContain('Outgoing raw edges')
    expect(selfProviderEndpointDetail).not.toContain('Incoming raw edges')
    expect(selfProviderEndpointDetail).toContain('<summary><h2>Raw data</h2></summary>')
    expect(selfProviderEndpointDetail).not.toContain('Data source')
    expect(selfProviderEndpointDetail).not.toContain('Source ID')
    expect(selfProviderEndpointDetail).not.toContain('Source URL')
    expect(selfProviderEndpointDetail).not.toContain('Pricing keys')
    expect(selfProviderEndpointDetail).not.toContain('未归一化源数据')
    const xiaomiSource = graph.nodes.find((candidate) => candidate.route === '/xiaomi/mimo-v2.5')
    expect(xiaomiSource).toBeTruthy()
    const xiaomiSourceDetail = renderOpenRouterRawDetail(graph, xiaomiSource!)
    expect(xiaomiSourceDetail).toContain('Xiaomi provider 报价')
    expect(xiaomiSourceDetail).not.toContain('canonical author 暂无自有报价')
    expect(xiaomiSourceDetail).not.toContain('Openrouter provider 报价')
    const palmyraSource = graph.nodes.find((candidate) => candidate.route === '/writer/palmyra-x5')
    expect(palmyraSource).toBeTruthy()
    const palmyraSourceDetail = renderOpenRouterRawDetail(graph, palmyraSource!)
    expect(palmyraSourceDetail).toContain('<h1>Writer: Palmyra X5</h1>')
    expect(palmyraSourceDetail).not.toContain('class="heroRelations"')
    expect(palmyraSourceDetail).not.toContain('class="relationChips"')
    expect(palmyraSourceDetail).toContain('Amazon provider 报价')
    expect(palmyraSourceDetail).toContain('data-price-source-provider="amazon"')
    expect(palmyraSourceDetail).toContain('data-usd="0.6"')
    expect(palmyraSourceDetail).toContain('data-usd="6"')
    expect(palmyraSourceDetail).toContain('其他 provider deployment 报价请点开查看')
    expect(palmyraSourceDetail).toContain('href="/openrouter/palmyra-x5/"')
    expect(palmyraSourceDetail).toContain('OpenRouter')
    expect(palmyraSourceDetail).not.toContain('href="/amazon/palmyra-x5/"')
    const palmyraOpenRouter = graph.nodes.find((candidate) => candidate.route === '/openrouter/palmyra-x5')
    expect(palmyraOpenRouter).toBeTruthy()
    const palmyraOpenRouterDetail = renderOpenRouterRawDetail(graph, palmyraOpenRouter!)
    expect(palmyraOpenRouterDetail).toContain('<h1>Writer: Palmyra X5</h1>')
    expect(palmyraOpenRouterDetail).toContain('Provider · OpenRouter')
    expect(palmyraOpenRouterDetail).toContain('href="/writer/palmyra-x5/"')
    expect(palmyraOpenRouterDetail).toContain('查看 canonical 模型页')
  })
})
