import { describe, expect, it } from 'vitest'
import { buildRegistryGraphFromFiles } from './registry-graph.js'
import { renderOpenRouterProviderDetail, renderOpenRouterRawDetail, renderOpenRouterRawHome } from './openrouter-raw-renderer.js'

describe('registry graph adapter', () => {
  const graph = buildRegistryGraphFromFiles()

  it('adapts data/models.json and data/providers/*.json to the plaza graph contract', () => {
    expect(graph.stats.sourceNodes).toBeGreaterThan(300)
    expect(graph.stats.endpointNodes).toBeGreaterThan(1000)
    expect(graph.stats.pricingObservations).toBeGreaterThan(1000)
    expect(graph.nodes.find((node) => node.route === '/openai/gpt-5.5')).toBeTruthy()
    expect(graph.nodes.find((node) => node.route === '/z-ai/glm-4.5')).toBeTruthy()
    expect(graph.schema.urlShape).toBe('/<provider>/<model-id>')
  })

  it('renders the current plaza, provider, and detail UI from the new registry graph', () => {
    const home = renderOpenRouterRawHome(graph)
    const writerVisibleRows = [...home.matchAll(/<tr data-model-row data-search-only="false"[^>]*data-model-author="writer"[\s\S]*?<\/tr>/gu)].map((match) => match[0])
    expect(writerVisibleRows).toHaveLength(1)
    expect(writerVisibleRows[0]).toContain('href="/writer/palmyra-x5/"')
    expect(writerVisibleRows[0]).not.toContain('href="/openrouter/palmyra-x5/"')
    expect(writerVisibleRows[0]).not.toContain('href="/amazon/palmyra-x5/"')
    expect(writerVisibleRows[0]).toContain('data-price-source-provider=')
    expect(writerVisibleRows[0]).toContain('priceValue')
    const provider = renderOpenRouterProviderDetail(graph, 'openai')
    const node = graph.nodes.find((candidate) => candidate.route === '/openai/gpt-5.5')
    expect(node).toBeTruthy()
    const detail = renderOpenRouterRawDetail(graph, node!)
    const titledNode = graph.nodes.find((candidate) => candidate.route === '/anthropic/claude-opus-4.6')
    expect(titledNode).toBeTruthy()
    const titledDetail = renderOpenRouterRawDetail(graph, titledNode!)

    expect(home).toContain('模型广场')
    expect(home).toContain('data-model-row')
    expect(home).toContain('GPT-5.5')
    expect(home).not.toContain('/new-models/')
    expect(provider).toContain('OpenAI')
    expect(provider).toContain('class="modelsShell providerShell"')
    expect(provider).toContain('<span>厂牌</span>')
    expect(provider).toContain('class="modelTable"')
    expect(provider).not.toContain('返回模型广场')
    expect(detail).toContain('Model ID')
    expect(detail).toContain('价格')
    expect(detail).toContain('数据来源与源数据')
    expect(titledNode!.displayName).toBe('Claude Opus 4.6')
    expect(titledDetail).toContain('<h1>Anthropic: Claude Opus 4.6</h1>')
    expect(titledDetail).toContain('<title>Anthropic: Claude Opus 4.6 · mddb.dev</title>')
    const openRouterEndpoint = graph.nodes.find((candidate) => candidate.route === '/openrouter/solar-pro-3')
    expect(openRouterEndpoint).toBeTruthy()
    const openRouterEndpointDetail = renderOpenRouterRawDetail(graph, openRouterEndpoint!)
    expect(openRouterEndpoint!.displayName).toBe('Solar Pro 3')
    expect(openRouterEndpointDetail).toContain('<h1>Upstage: Solar Pro 3</h1>')
    expect(openRouterEndpointDetail).toContain('<title>Upstage: Solar Pro 3 · mddb.dev</title>')
    expect(openRouterEndpointDetail).toContain('Provider · OpenRouter')
    expect(openRouterEndpointDetail).not.toContain('class="relationChips"')
    expect(openRouterEndpointDetail).toContain('查看 canonical 模型页')
    const palmyraSource = graph.nodes.find((candidate) => candidate.route === '/writer/palmyra-x5')
    expect(palmyraSource).toBeTruthy()
    const palmyraSourceDetail = renderOpenRouterRawDetail(graph, palmyraSource!)
    expect(palmyraSourceDetail).toContain('<h1>Writer: Palmyra X5</h1>')
    expect(palmyraSourceDetail).toContain('在其他 provider 查看 deployment 与报价')
    expect(palmyraSourceDetail).toContain('href="/openrouter/palmyra-x5/"')
    expect(palmyraSourceDetail).toContain('OpenRouter')
    expect(palmyraSourceDetail).toContain('href="/amazon/palmyra-x5/"')
    expect(palmyraSourceDetail).toContain('Amazon')
    const palmyraOpenRouter = graph.nodes.find((candidate) => candidate.route === '/openrouter/palmyra-x5')
    expect(palmyraOpenRouter).toBeTruthy()
    const palmyraOpenRouterDetail = renderOpenRouterRawDetail(graph, palmyraOpenRouter!)
    expect(palmyraOpenRouterDetail).toContain('<h1>Writer: Palmyra X5</h1>')
    expect(palmyraOpenRouterDetail).toContain('Provider · OpenRouter')
    expect(palmyraOpenRouterDetail).toContain('href="/writer/palmyra-x5/"')
    expect(palmyraOpenRouterDetail).toContain('查看 canonical 模型页')
  })
})
