const css = `
:root{color-scheme:light dark;--bg:#f7f4ef;--panel:#fffaf2;--ink:#17130d;--muted:#756b5d;--line:#ded4c4;--accent:#111827;--disabled:#e7dfd2;--good:#136f3f;--warn:#9a5a00}*{box-sizing:border-box}body{margin:0;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:radial-gradient(circle at top left,#fff 0,#f7f4ef 42%,#eee6d8 100%);color:var(--ink)}main{max-width:1120px;margin:0 auto;padding:32px 20px 48px}.top{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;margin-bottom:24px}.eyebrow{font-size:12px;letter-spacing:.18em;text-transform:uppercase;color:var(--muted);margin:0 0 8px}h1{font-size:34px;line-height:1.1;margin:0 0 10px}.muted{color:var(--muted);line-height:1.7}.card{background:color-mix(in srgb,var(--panel) 92%,white);border:1px solid var(--line);border-radius:22px;box-shadow:0 20px 60px #61410d14;padding:22px}.login{display:grid;gap:12px;max-width:420px}.login input{width:100%;border:1px solid var(--line);border-radius:14px;padding:12px 14px;font:inherit;background:#fff}.button{border:0;border-radius:999px;background:var(--accent);color:white;padding:11px 16px;font-weight:650;cursor:pointer}.button.secondary{background:#fff;color:var(--ink);border:1px solid var(--line)}.button:disabled{background:var(--disabled);color:#8d8374;cursor:not-allowed}.sources{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px;margin:20px 0}.source{display:flex;flex-direction:column;gap:10px;min-height:170px}.source h2{font-size:18px;margin:0}.badge{width:max-content;border:1px solid var(--line);border-radius:999px;padding:4px 9px;font-size:12px;color:var(--muted)}.badge.ready{color:var(--good);border-color:color-mix(in srgb,var(--good) 35%,var(--line))}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:auto}.workspace{display:grid;grid-template-columns:320px 1fr;gap:16px}.log{white-space:pre-wrap;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px;background:#17130d;color:#f8efe0;border-radius:18px;padding:16px;min-height:360px;overflow:auto}.summary{display:grid;gap:10px}.summary .stat{display:flex;justify-content:space-between;border-bottom:1px solid var(--line);padding-bottom:8px}.hidden{display:none!important}@media(max-width:880px){.sources,.workspace{grid-template-columns:1fr}.top{display:block}}
`;

export function renderUpdateAdminPage(): string {
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>数据同步 · mddb.dev</title><style>${css}</style></head><body><main><section class="top"><div><p class="eyebrow">Internal Update</p><h1>内部数据同步</h1><p class="muted">管理员工具：先输入密码，再预览数据源更新造成的 diff；确认后才写入仓库数据文件。密码由服务端环境变量读取，页面不嵌入任何密钥。</p></div><a class="button secondary" href="/">返回模型广场</a></section><section id="login" class="card login" aria-label="管理员登录"><label><span class="muted">管理员密码</span><input id="password" type="password" autocomplete="current-password" placeholder="输入同步工具密码"></label><button id="unlock" class="button">进入</button><p id="loginMessage" class="muted" role="status"></p></section><section id="console" class="hidden" aria-label="数据源同步控制台"><div class="sources">${renderSourceCards()}</div><div class="workspace"><aside class="card summary"><h2>本次预览</h2><div class="stat"><span>数据源</span><b id="activeSource">—</b></div><div class="stat"><span>变更文件</span><b id="changedFiles">0</b></div><div class="stat"><span>状态</span><b id="runStatus">等待操作</b></div><button id="apply" class="button" disabled>确认写入</button><p class="muted">确认前不会修改工作区。写入后仍需管理员在仓库内 review、commit、deploy。</p></aside><section><pre id="diff" class="log">点击“预览 diff”开始读取数据。</pre></section></div></section><script>${clientJs()}</script></main></body></html>`
}

function renderSourceCards(): string {
  const sources = [
    { id: 'openrouter', name: 'OpenRouter', enabled: true, note: '已接入脚本：抓取模型、端点、页面补充，并生成 registry 数据。' },
    { id: 'models-dev', name: 'models.dev', enabled: false, note: '占位：后续接入为 OpenRouter-first 数据补充。' },
    { id: 'basellm', name: 'BaseLLM', enabled: false, note: '占位：后续接入价格/可用性补充。' },
    { id: 'litellm', name: 'LiteLLM', enabled: false, note: '占位：后续接入模型价格补充。' },
  ]
  return sources.map((source) => `<article class="card source" data-source-id="${source.id}" data-enabled="${source.enabled}"><span class="badge ${source.enabled ? 'ready' : ''}">${source.enabled ? '可点击' : '占位'}</span><h2>${source.name}</h2><p class="muted">${source.note}</p><div class="actions"><button class="button" data-preview="${source.id}" ${source.enabled ? '' : 'disabled'}>预览 diff</button></div></article>`).join('')
}

function clientJs(): string {
  return `
const state={password:'',patchFile:null,source:null};
const $=(id)=>document.getElementById(id);
$('unlock').addEventListener('click',async()=>{state.password=$('password').value;const res=await fetch('/api/update/session',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({password:state.password})});if(res.ok){$('login').classList.add('hidden');$('console').classList.remove('hidden');$('loginMessage').textContent=''}else{$('loginMessage').textContent='密码不正确'}});
document.querySelectorAll('[data-preview]').forEach((button)=>button.addEventListener('click',async()=>{const source=button.dataset.preview;state.source=source;state.patchFile=null;$('apply').disabled=true;$('activeSource').textContent=source;$('runStatus').textContent='读取中';$('diff').textContent='正在运行数据同步脚本并计算 diff…';const endpoint=source==='openrouter'?'/api/update/openrouter/preview':'/api/update/'+source+'/preview';const res=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({password:state.password})});const data=await res.json().catch(()=>({ok:false,error:'响应不是 JSON'}));if(!res.ok||!data.ok){$('runStatus').textContent='失败';$('diff').textContent=data.error||'预览失败';return;}state.patchFile=data.patchFile;$('changedFiles').textContent=String((data.changedFiles||[]).length);$('runStatus').textContent='等待确认';$('diff').textContent=data.diff||'没有变更';$('apply').disabled=!data.patchFile;}));
$('apply').addEventListener('click',async()=>{if(!state.patchFile||!state.source)return;$('runStatus').textContent='写入中';const endpoint=state.source==='openrouter'?'/api/update/openrouter/apply':'/api/update/'+state.source+'/apply';const res=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({password:state.password,patchFile:state.patchFile})});const data=await res.json().catch(()=>({ok:false,error:'响应不是 JSON'}));if(!res.ok||!data.ok){$('runStatus').textContent='写入失败';$('diff').textContent=data.error||'写入失败';return;}$('runStatus').textContent='已写入';$('apply').disabled=true;});`
}
